[package]
name = "meta-ad-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
fantoccini = "0.21.2"
scraper = "0.21.0"
